############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Le Crieur"
url = "crieur/"
weight = 2

[[main]]
name = "Fringale"
url = "fringale/"
weight = 3

# [[main]]
# name = "Rubriques"
# isParent = true
# weight = 4

# [[main]]
# name = "Événements"
# url = "events/"
# parent = "Rubriques"

[[main]]
name = "Recettes"
url = "recettes/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "L'association"
url = "association/"
weight = 5


# footer menu
[[footer]]
name = "A propos"
url = "association/"
weight = 1

[[footer]]
weight = 2
name = "Contact"
url = "mailto:epfl180c@gmail.com"

# FIXME:set it to the 180c repo when merged
[[footer]]
weight = 3
name = "Github"
url = "https://github.com/eliott8942/site-180"