######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "/"
# Title of your website (required).
title = "180Â°C"
# Your theme name
theme = "hugoplate"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Europe/Zurich"
# post pagination
pagination.pagerSize = 2 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# disable language
disableLanguages = [ "en" ] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

defaultContentLanguage = "fr"

[taxonomies]
    blog_categories = "blog/categories"
    blog_tags = "blog/tags"
    recettes_categories = "recettes/categories"
    recettes_tags = "recettes/tags"


########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorcontentbasename/"


############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]


########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
# Glightbox loaded conditionally on gallery pages
# link = "plugins/glightbox/glightbox.css"
# Font Awesome - only solid.css needed (brands and icons unused)
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
# Swiper - always loaded (needed for testimonials on homepage)
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"

# Glightbox - loaded conditionally for image galleries
# link = "plugins/glightbox/glightbox.js"

# Gallery and UI components - remove if not used
# link = "js/gallery-slider.js"
# link = "js/accordion.js"
# link = "js/tab.js"
# link = "js/modal.js"

# Cookie consent - disabled
# link = "plugins/cookie.js"

# YouTube lazy load - disabled
# link = "plugins/youtube-lite.js"

# jQuery - REMOVED (35KB) - replaced with vanilla JS
# link = "plugins/jquery/jquery-3.6.0.min.js"

# Map libraries - loaded only on map pages
# link = "https://cdn.jsdelivr.net/npm/ol@v7.1.0/dist/ol.js"
# link = "https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.12/proj4.js"
# link = "https://epsg.io/21781.js"
# link = "https://epsg.io/2056.js"